name: Reporte de Error (Bug)
description: Notifica un fallo o comportamiento inesperado en bot-factory
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: >
        ### ¡Gracias por reportar este problema!
        Asegúrate de proporcionar la información necesaria para reproducir el fallo.
  - id: descripcion
    type: textarea
    attributes:
      label: Descripción del problema
      description: Describe brevemente qué sucedió y qué esperabas que pasara.
      placeholder: Al ejecutar el script, el bot responde con...
    validations:
      required: true
  - id: pasos
    type: textarea
    attributes:
      label: Pasos para reproducir
      description: Comandos o código utilizado.
      placeholder: |
        1. Ejecutar python bridge.py
        2. ...
    validations:
      required: true
  - id: entorno
    type: dropdown
    attributes:
      label: Entorno de ejecución
      description: ¿Dónde ocurrió el error?
      options:
        - Termux
        - Codespaces / Workspace
        - GitHub Actions
        - Servidor Externo
    validations:
      required: true
