name: Reportar un Error (Bug)
description: Informa sobre un fallo en los flujos o automatizaciones.
title: '[Bug]: '
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: >
        ### ¡Gracias por reportar este problema!
        Describe el fallo detectado en los workflows o scripts del repositorio.
  - id: mvce
    type: textarea
    attributes:
      label: Pasos para reproducir o Log del error
      description: Pega aquí los logs de GitHub Actions o describe cómo se activa el fallo.
      placeholder: |
        - Acción ejecutada: ...
        - Error recibido en los logs: ...
    validations:
      required: true
  - id: expectation
    type: textarea
    attributes:
      label: Resultado esperado
      placeholder: |
        El job de GitHub Actions debió finalizar en verde exitosamente...
    validations:
      required: true
  - id: environment
    type: dropdown
    attributes:
      label: Entorno de ejecución
      description: ¿Dónde se produjo la falla?
      options:
        - GitHub Actions Runner (Ubuntu / CI-CD)
        - Servidor / API remota
        - Otro
    validations:
      required: true
