name: Nueva Función (Feature Request)
description: Sugiere una nueva idea, automatización o mejora para el proyecto.
title: '[Feature]: '
type: 'Feature'
body:
  - type: markdown
    attributes:
      value: |
        ### ¡Gracias por sugerir una mejora o nueva función!
        Describe la idea o automatización que te gustaría incorporar a los workflows o scripts.
  - type: textarea
    id: summary
    attributes:
      label: Descripción de la función
      description: Explica detalladamente qué debería hacer esta nueva característica o mejora.
      placeholder: |
        Me gustaría agregar un nuevo workflow/script que se encargue de...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Caso de uso / Beneficio
      description: ¿Qué problema resuelve o qué proceso automatiza esta propuesta?
      placeholder: |
        Esto ayudará a automatizar el proceso de...
    validations:
      required: false
