name: Solicitud de Funcionalidad (Feature)
description: Sugiere una nueva idea o mejora para bot-factory
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: |
        ### ¡Gracias por sugerir una mejora para bot-factory!
        Por favor, detalla la propuesta para entender cómo beneficiaría al proyecto.
  - type: textarea
    id: resumen
    attributes:
      label: Descripción de la funcionalidad
      description: Explica detalladamente qué te gustaría que haga el bot o qué mejora propones.
      placeholder: Me gustaría que el bot pudiera...
    validations:
      required: true
  - type: textarea
    id: caso_de_uso
    attributes:
      label: Caso de uso / Motivación
      description: ¿Qué problema resuelve esta nueva función o por qué sería útil?
      placeholder: Esto facilitaría...
    validations:
      required: false
