blank_issues_enabled: false
contact_links:
  - name: Preguntas sobre bot-factory
    url: https://github.com/moranricardo/bot-factory/discussions
    about: Para dudas generales o guía de uso, por favor abre un hilo en la sección de Discusiones del proyecto.
